services:
  - type: web
    name: features-selection-svu
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    pythonVersion: 3.10.0
